#!/usr/bin/env node
/**
 * Tenant helper: list / use / validate / dev / build
 * Usage: node scripts/tenant.mjs <command> [tenantId]
 */
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const REGISTRY_PATH = path.join(ROOT, "lib", "tenants", "registry.json");
const ACTIVE_PATH = path.join(ROOT, "lib", "tenants", "active.ts");
const ENV_TENANTS_DIR = path.join(ROOT, ".env.tenants");
const ENV_LOCAL_PATH = path.join(ROOT, ".env.local");
const PUBLIC_TENANTS_DIR = path.join(ROOT, "public", "tenants");
const INACTIVE_DIR = path.join(ROOT, ".tenant-inactive");

const REQUIRED_ENV_KEYS = [
  "NEXT_PUBLIC_TENANT_ID",
  "NEXT_PUBLIC_API_KEY",
  "NEXT_PUBLIC_AUTH_DOMAIN",
  "NEXT_PUBLIC_PROJECT_ID",
  "NEXT_PUBLIC_STORAGE_BUCKET",
  "NEXT_PUBLIC_MESSAGING_SENDER_ID",
  "NEXT_PUBLIC_APP_ID",
];

function loadRegistry() {
  const raw = fs.readFileSync(REGISTRY_PATH, "utf8");
  return JSON.parse(raw);
}

function assertTenantId(id) {
  if (!id) {
    fail("Tenant id gerekli. Örnek: npm run tenant:use -- biladerler");
  }
  const registry = loadRegistry();
  if (!registry[id]) {
    fail(
      `Bilinmeyen tenant "${id}". Kayıtlı: ${Object.keys(registry).join(", ")}`,
    );
  }
  return registry;
}

function fail(message) {
  console.error(`Error: ${message}`);
  process.exit(1);
}

function parseEnvFile(filePath) {
  const text = fs.readFileSync(filePath, "utf8");
  const map = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    map[key] = value;
  }
  return map;
}

function envPathFor(id) {
  return path.join(ENV_TENANTS_DIR, `${id}.env`);
}

function writeActiveTs(id, entry) {
  const contents = `/* AUTO-GENERATED by scripts/tenant.mjs - do not edit by hand */
import { ${entry.exportName} } from "${entry.importPath}";
import type { TenantConfig } from "./types";

export const activeTenant: TenantConfig = ${entry.exportName};
`;
  fs.writeFileSync(ACTIVE_PATH, contents, "utf8");
  console.log(`Wrote lib/tenants/active.ts → ${id}`);
}

function copyEnvLocal(id) {
  const src = envPathFor(id);
  if (!fs.existsSync(src)) {
    fail(
      `Env dosyası yok: .env.tenants/${id}.env\n  Şablon: .env.tenants/${id}.env.example`,
    );
  }
  fs.copyFileSync(src, ENV_LOCAL_PATH);
  console.log(`Wrote .env.local from .env.tenants/${id}.env`);
}

function validateTenant(id, { requireFilled = true } = {}) {
  const registry = assertTenantId(id);
  const src = envPathFor(id);
  if (!fs.existsSync(src)) {
    fail(`Env dosyası yok: .env.tenants/${id}.env`);
  }
  const env = parseEnvFile(src);
  const missing = [];
  const empty = [];

  for (const key of REQUIRED_ENV_KEYS) {
    if (!(key in env)) missing.push(key);
    else if (requireFilled && !String(env[key]).trim()) empty.push(key);
  }

  if (env.NEXT_PUBLIC_TENANT_ID && env.NEXT_PUBLIC_TENANT_ID !== id) {
    fail(
      `NEXT_PUBLIC_TENANT_ID="${env.NEXT_PUBLIC_TENANT_ID}" dosyadaki tenant id ile uyuşmuyor (beklenen: ${id})`,
    );
  }

  if (missing.length) {
    fail(`Eksik env anahtarları (${id}): ${missing.join(", ")}`);
  }
  if (empty.length) {
    fail(`Boş env değerleri (${id}): ${empty.join(", ")}`);
  }

  console.log(`Validated tenant "${id}"`);
  return registry;
}

function cmdList() {
  const ids = Object.keys(loadRegistry());
  console.log(ids.length ? ids.join("\n") : "(no tenants)");
}

function cmdUse(id) {
  const registry = assertTenantId(id);
  // use: allow empty Firebase for local bootstrap, but TENANT_ID must match if present
  const src = envPathFor(id);
  if (!fs.existsSync(src)) {
    fail(
      `Env dosyası yok: .env.tenants/${id}.env\n  cp .env.tenants/${id}.env.example .env.tenants/${id}.env`,
    );
  }
  const env = parseEnvFile(src);
  if (env.NEXT_PUBLIC_TENANT_ID && env.NEXT_PUBLIC_TENANT_ID !== id) {
    fail(
      `NEXT_PUBLIC_TENANT_ID="${env.NEXT_PUBLIC_TENANT_ID}" dosyadaki tenant id ile uyuşmuyor (beklenen: ${id})`,
    );
  }
  writeActiveTs(id, registry[id]);
  copyEnvLocal(id);
}

function hideInactivePublicTenants(activeId) {
  if (!fs.existsSync(PUBLIC_TENANTS_DIR)) return [];
  fs.mkdirSync(INACTIVE_DIR, { recursive: true });
  const moved = [];
  for (const name of fs.readdirSync(PUBLIC_TENANTS_DIR)) {
    if (name === activeId) continue;
    const from = path.join(PUBLIC_TENANTS_DIR, name);
    if (!fs.statSync(from).isDirectory()) continue;
    const to = path.join(INACTIVE_DIR, name);
    if (fs.existsSync(to)) {
      fs.rmSync(to, { recursive: true, force: true });
    }
    fs.renameSync(from, to);
    moved.push(name);
  }
  if (moved.length) {
    console.log(`Hid inactive public tenants: ${moved.join(", ")}`);
  }
  return moved;
}

function restoreInactivePublicTenants() {
  if (!fs.existsSync(INACTIVE_DIR)) return;
  fs.mkdirSync(PUBLIC_TENANTS_DIR, { recursive: true });
  for (const name of fs.readdirSync(INACTIVE_DIR)) {
    const from = path.join(INACTIVE_DIR, name);
    const to = path.join(PUBLIC_TENANTS_DIR, name);
    if (fs.existsSync(to)) {
      fs.rmSync(to, { recursive: true, force: true });
    }
    fs.renameSync(from, to);
  }
  fs.rmSync(INACTIVE_DIR, { recursive: true, force: true });
  console.log("Restored inactive public tenants");
}

function runNext(args) {
  return new Promise((resolve, reject) => {
    const child = spawn("npx", ["next", ...args], {
      cwd: ROOT,
      stdio: "inherit",
      shell: true,
      env: process.env,
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`next ${args.join(" ")} exited with ${code}`));
    });
  });
}

async function cmdDev(id) {
  cmdUse(id);
  await runNext(["dev"]);
}

async function cmdBuild(id) {
  validateTenant(id, { requireFilled: true });
  const registry = loadRegistry();
  writeActiveTs(id, registry[id]);
  copyEnvLocal(id);

  let buildError;
  try {
    hideInactivePublicTenants(id);
    await runNext(["build"]);
    console.log(`Build OK for tenant "${id}"`);
  } catch (err) {
    buildError = err;
  } finally {
    try {
      restoreInactivePublicTenants();
    } catch (restoreErr) {
      console.error("Failed to restore public tenants:", restoreErr);
    }
  }
  if (buildError) {
    console.error(buildError.message || buildError);
    process.exit(1);
  }
}

function printHelp() {
  console.log(`Baglama Store tenant helper

Commands:
  list                 List registered tenant ids
  use <id>             Write active.ts + .env.local
  validate <id>        Validate .env.tenants/<id>.env
  dev <id>             use + next dev
  build <id>           validate + use + hide other logos + next build

Examples:
  npm run tenant:list
  npm run tenant:use -- biladerler
  npm run build:tenant -- ornek
`);
}

const [command, tenantId] = process.argv.slice(2);

switch (command) {
  case "list":
    cmdList();
    break;
  case "use":
    cmdUse(tenantId);
    break;
  case "validate":
    validateTenant(tenantId, { requireFilled: true });
    break;
  case "dev":
    await cmdDev(tenantId);
    break;
  case "build":
    await cmdBuild(tenantId);
    break;
  case "help":
  case undefined:
    printHelp();
    break;
  default:
    fail(`Bilinmeyen komut "${command}". help için: node scripts/tenant.mjs help`);
}
