/* AUTO-GENERATED by scripts/tenant.mjs - do not edit by hand */
import { biladerlerTenant } from "./biladerler";
import type { TenantConfig } from "./types";

export const activeTenant: TenantConfig = biladerlerTenant;
