/* AUTO-GENERATED by scripts/tenant.mjs - do not edit by hand */
import { bestekarTenant } from "./bestekar";
import type { TenantConfig } from "./types";

export const activeTenant: TenantConfig = bestekarTenant;
